baseURL = "/"
languageCode = "en-us"
title = "Eredis Gutierrez"
theme = "etch"
paginate = 5

copyright = "© Eredis Gutierrez."

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
	subtitle = "Software & Security Engineer"

	mode = "auto" # "dark" or "auto"

	highlight = true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/eredisg"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
